[package]
name = "hell"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/charlesrocket/hell"
authors = ["charlesrocket"]
readme = "README.md"

[dependencies]
bootloader = "0.10.13"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
