name: tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add rustfmt
      - name: Check
        run: cargo fmt --check --verbose
